### ISSUE TITLE
Needs updating to Blender 2.8x

### ISSUE THREAD

**Issue by drewc5131** [rdb/blender-egg-importer#10]
Blender 2.8x was a MASSIVE update to blender, which also means every plugin was destroyed in the process, including this one.

**Comment by rdb** [comment]
Updated; the plug-in should now work with Blender 2.80 (while still supporting Blender 2.74-2.79).  Materials with textures are converted to node-based materials.  I tested it to work on a bunch of sample models.  If you can still find models with errors, then please file individual bugs for those.
