### ISSUE TITLE
Vertex coloring is not supported in 2.79b

### ISSUE THREAD

**Issue by JustDirectCode** [rdb/blender-egg-importer#19]
I've written a script to fix the importing of all .egg files in 2.79b and it works flawlessly, but vertex colors are not imported in 2.79b, meaning I'd have to rewrite the whole script to work with 2.8 which isn't a very viable solution for the project I'm working on.

2.79b
![image](https://user-images.githubusercontent.com/35377679/118412938-a388d200-b694-11eb-97d1-03f7c6018dfc.png)

2.8
![image](https://user-images.githubusercontent.com/35377679/118412945-aaafe000-b694-11eb-8348-429254df0481.png)

**Comment by rdb** [comment]
I'll check later, but I'm fairly sure vertex colors are supported all the same.  Are you not seeing Col data in the mesh info panel?

However, Blender's material model changed between versions, and you may need to enable Vertex Color Paint for the material,

**Comment by JustDirectCode** [comment]
You're correct in that Vertex Color Paint wasn't enabled, but unfortunately that didn't make a difference when I enabled it :/ 

Interestingly, y

**Comment by JustDirectCode** [comment]
I apologise. I'm a complete idiot! I forgot to enter "texture" mode instead of "material" or "render" mode which shows it up fine.
