### ISSUE TITLE
Error when loading Roaming Ralph world

### ISSUE THREAD

**Issue by Moguri** [rdb/blender-egg-importer#5]
I get the below error when attempting to load the world.egg.pz from the Roaming Ralph demo. I also do not see the trees and rocks. The script likely died before handling them.

```
MESH: terrain
mesh_validate_customdata: Checking 1 CD layers...
mesh_validate_customdata: Finished (is_valid=1)

mesh_validate_customdata: Checking 1 CD layers...
mesh_validate_customdata: Finished (is_valid=1)

mesh_validate_customdata: Checking 2 CD layers...
mesh_validate_customdata: Finished (is_valid=1)

mesh_validate_customdata: Checking 2 CD layers...
mesh_validate_customdata: Finished (is_valid=1)

BKE_mesh_validate_arrays: verts(1089), edges(2108), loops(4080), polygons(1020)
BKE_mesh_validate_arrays: finished

Error: Array length mismatch (got 1632, expected more)
Traceback (most recent call last):
  File "/home/mitchell/.config/blender/2.79/scripts/addons/blender-egg-importer-master/__init__.py", line 55, in execute
    root.build_tree(context)
  File "/home/mitchell/.config/blender/2.79/scripts/addons/blender-egg-importer-master/importer.py", line 783, in build_tree
    child.build_tree(context, parent, inv_matrix, under_dart)
  File "/home/mitchell/.config/blender/2.79/scripts/addons/blender-egg-importer-master/importer.py", line 1043, in build_tree
    cols.data.foreach_set('color', self.vertex_colors)
RuntimeError: internal error setting the array

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by rdb** [comment]
That's odd.  I'm also using Blender 2.79, and I managed to import `world.egg.pz` correctly.  Is this the original file or had you made local changes to the model?

**Comment by Moguri** [comment]
I was probably testing this using the version from the `pushy_ralph` branch, which had modifications. I tried the version from `master`, but I got the same results.

**Comment by rdb** [comment]
Actually, apparently it's ArchLinux that's the odd one out; it's using a pre-release version of 2.79c (which was never released), which [adds an alpha channel to vertex colors](https://forums.unrealengine.com/development-discussion/content-creation/1513940-blender-2-79c-finally-supports-the-vertex-paint-alpha-channel).

I think we might to check `bpy.app.version_char`, then, to determine whether to add an alpha channel to vertex colors.
