### ISSUE TITLE
Animation Support?

### ISSUE THREAD

**Issue by Fire70054** [rdb/blender-egg-importer#9]
Currently this was last updated about two years ago. Is importing skeletal mesh animation still planned to come, or is this no longer being worked on? This seems to be the closest to the possibility of importing bam/egg animations so far

**Comment by rdb** [comment]
Already supported, see #1.  If you have a model with animations that is not being imported correctly, please share it.

**Comment by Fire70054** [comment]
Here's a few samples of models. I'm attempting to import a few from Toontown Online. I haven't gotten animations to import successfully far. 
Occasionally meshes won't import as well. I believe it's usually the newer meshes that have that issue.
[Models.zip](https://github.com/rdb/blender-egg-importer/files/3399923/Models.zip)

**Comment by rdb** [comment]
Since you indicated that you don't own the rights to these assets, I can't be helping you with this.  If you can reproduce the issue with a model you own, or obtain written permission from the author, please file a new issue.
